---
version: "3.2"
services:

  common: &common
    image: ansible
    build:
      context: ./
      dockerfile: './build/Dockerfile'
    volumes:
      - shared:/app
    env_file:
      - .env

# - install ansible roles ;
  install:
    <<: *common
    container_name: "ansible-install"
    command:
      - |
        ansible-galaxy \
        install \
        -r \
        requirements.yml

# - append private key to ssh client;
# - evaluate ansible playbook;
  play:
    <<: *common
    container_name: "ansible-playbook"
    command:
      - |
        eval $(ssh-agent); 
        ssh-add - <<< "${TARGET_ID_RSA}";

        ansible-playbook \
        ./playbooks/playbook.yml \
        --inventory \
        ./inventories/hosts;

volumes:
  shared:
...
